package auto;

import java.io.IOException;
import java.time.Clock;
import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import auto.command.Command;
import auto.exception.AutoException;
import auto.parser.Parser;
import auto.storage.Storage;
import auto.task.Task;
import auto.task.TaskList;
import auto.util.DateUtil;

/** Coordinates Auto's storage, UI, task list, and command execution loop. */
public class Auto {
    private static final String DEFAULT_DATA_FILE = "data/auto.txt";
    private final Storage storage;
    private final TaskList tasks;
    private final String startupMessage;

    /** Creates an Auto application using the configured or default data file. */
    public Auto() {
        this(System.getProperty("auto.data.file", DEFAULT_DATA_FILE));
    }

    /**
     * Creates an Auto application that persists tasks at the specified file path.
     *
     * @param filePath Path of the file used to load and save tasks.
     */
    public Auto(String filePath) {
        this(filePath, Clock.systemDefaultZone());
    }

    /** Creates an application with a controllable clock for startup reminders. */
    Auto(String filePath, Clock clock) {
        storage = new Storage(filePath);
        LoadOutcome loadOutcome = loadTasks();
        tasks = loadOutcome.tasks();
        startupMessage = createStartupMessage(loadOutcome.message(), LocalDate.now(clock));
    }

    /**
     * Executes one command and returns the response generated by Auto.
     *
     * @param input User command to parse and execute.
     * @return Rendered response suitable for display in a chat interface.
     */
    public String getResponse(String input) {
        try {
            Command command = Parser.parse(input);
            return command.execute(tasks, storage).message();
        } catch (AutoException e) {
            return e.getMessage();
        }
    }

    /**
     * Returns storage warnings and reminders captured when the application opens.
     *
     * @return Startup details, or an empty string when there are none.
     */
    public String getStartupMessage() {
        return startupMessage;
    }

    /** Combines any load warning with today's tasks, retaining their list numbers. */
    private String createStartupMessage(String warning, LocalDate today) {
        List<Task> savedTasks = tasks.asList();
        String reminders = IntStream.range(0, savedTasks.size())
                .filter(i -> savedTasks.get(i).occursOn(today))
                .mapToObj(i -> String.format("%d. %s", i + 1, savedTasks.get(i)))
                .collect(Collectors.joining(System.lineSeparator()));
        String message = warning == null ? "" : warning;
        if (reminders.isEmpty()) {
            return message;
        }
        if (!message.isEmpty()) {
            message += System.lineSeparator() + System.lineSeparator();
        }
        return message + "Eh, remember these tasks for today (" + DateUtil.format(today) + "):"
                + System.lineSeparator() + reminders;
    }

    /** Loads saved tasks, recovering cleanly when the file cannot be used. */
    private LoadOutcome loadTasks() {
        try {
            Storage.LoadResult result = storage.load();
            String message = null;
            if (!result.warnings().isEmpty()) {
                message = String.format(
                        "Paiseh, some saved data cannot be read. %d invalid data line(s) were skipped: %s.",
                        result.warnings().size(), String.join(", ", result.warnings()));
            }
            return new LoadOutcome(new TaskList(result.tasks()), message);
        } catch (IOException | RuntimeException e) {
            return new LoadOutcome(
                    new TaskList(),
                    "Paiseh, I couldn't load your saved tasks. Starting with an empty task list.");
        }
    }

    /** Holds tasks and any user-facing warning produced while loading them. */
    private record LoadOutcome(TaskList tasks, String message) {
    }
}
