package auto;

import java.io.IOException;

import auto.command.Command;
import auto.exception.AutoException;
import auto.parser.Parser;
import auto.storage.Storage;
import auto.task.TaskList;

/** Coordinates Auto's storage, UI, task list, and command execution loop. */
public class Auto {
    private static final String DEFAULT_DATA_FILE = "data/auto.txt";
    private final Storage storage;
    private final TaskList tasks;
    private final String startupMessage;

    /** Creates an Auto application using the configured or default data file. */
    public Auto() {
        this(System.getProperty("auto.data.file", DEFAULT_DATA_FILE));
    }

    /**
     * Creates an Auto application that persists tasks at the specified file path.
     *
     * @param filePath Path of the file used to load and save tasks.
     */
    public Auto(String filePath) {
        storage = new Storage(filePath);
        LoadOutcome loadOutcome = loadTasks();
        tasks = loadOutcome.tasks();
        startupMessage = loadOutcome.message();
    }

    /**
     * Executes one command and returns the response generated by Auto.
     *
     * @param input User command to parse and execute.
     * @return Rendered response suitable for display in a chat interface.
     */
    public String getResponse(String input) {
        try {
            Command command = Parser.parse(input);
            return command.execute(tasks, storage).message();
        } catch (AutoException e) {
            return e.getMessage();
        }
    }

    /**
     * Returns the warning produced while loading storage, if any.
     *
     * @return Pending storage warning, or an empty string when there is none.
     */
    public String getStartupMessage() {
        return startupMessage == null ? "" : startupMessage;
    }

    /** Loads saved tasks, recovering cleanly when the file cannot be used. */
    private LoadOutcome loadTasks() {
        try {
            Storage.LoadResult result = storage.load();
            String message = null;
            if (!result.warnings().isEmpty()) {
                message = String.format(
                        "Warning: %d invalid data line(s) were skipped: %s.",
                        result.warnings().size(), String.join(", ", result.warnings()));
            }
            return new LoadOutcome(new TaskList(result.tasks()), message);
        } catch (IOException | RuntimeException e) {
            return new LoadOutcome(
                    new TaskList(),
                    "Sorry, I couldn't load your saved tasks. Starting with an empty task list.");
        }
    }

    /** Holds tasks and any user-facing warning produced while loading them. */
    private record LoadOutcome(TaskList tasks, String message) {
    }
}
