package auto;

import java.io.IOException;

import auto.command.Command;
import auto.exception.AutoException;
import auto.parser.Parser;
import auto.storage.Storage;
import auto.task.TaskList;
import auto.ui.Ui;

/** Coordinates Auto's storage, UI, task list, and command execution loop. */
public class Auto {
    private static final String DEFAULT_DATA_FILE = "data/auto.txt";
    private final Storage storage;
    private final Ui ui;
    private final TaskList tasks;
    private final String startupMessage;
    private boolean isStartupMessageShown;

    /** Creates an Auto application using the configured or default data file. */
    public Auto() {
        this(System.getProperty("auto.data.file", DEFAULT_DATA_FILE));
    }

    /**
     * Creates an Auto application that persists tasks at the specified file path.
     *
     * @param filePath Path of the file used to load and save tasks.
     */
    public Auto(String filePath) {
        storage = new Storage(filePath);
        ui = new Ui();
        LoadOutcome loadOutcome = loadTasks();
        tasks = loadOutcome.tasks();
        startupMessage = loadOutcome.message();
    }

    /**
     * Launches Auto using the configured data-file property or the default data
     * file.
     *
     * @param args Command-line arguments, which are currently unused.
     */
    public static void main(String[] args) {
        new Auto().run();
    }

    /** Starts the interaction loop and releases UI resources on exit. */
    public void run() {
        ui.showWelcome();
        showStartupMessage(ui);

        try {
            boolean isRunning = true;
            while (isRunning) {
                String userInput = ui.readCommand();

                try {
                    Command command = Parser.parse(userInput);
                    command.execute(tasks, ui, storage);
                    isRunning = !command.isExit();
                } catch (AutoException e) {
                    ui.showError(e.getMessage());
                }
            }
        } finally {
            ui.close();
        }
    }

    /**
     * Executes one command and returns the response generated by Auto.
     *
     * @param input User command to parse and execute.
     * @return Rendered response suitable for display in a chat interface.
     */
    public String getResponse(String input) {
        StringBuilder response = new StringBuilder();
        Ui responseUi = new Ui(message -> appendResponse(response, message));
        showStartupMessage(responseUi);

        try {
            Command command = Parser.parse(input);
            command.execute(tasks, responseUi, storage);
        } catch (AutoException e) {
            responseUi.showError(e.getMessage());
        }

        return response.toString();
    }

    /** Loads saved tasks, recovering cleanly when the file cannot be used. */
    private LoadOutcome loadTasks() {
        try {
            Storage.LoadResult result = storage.load();
            String message = null;
            if (!result.warnings().isEmpty()) {
                message = String.format(
                        "Warning: %d invalid data line(s) were skipped: %s.",
                        result.warnings().size(), String.join(", ", result.warnings()));
            }
            return new LoadOutcome(new TaskList(result.tasks()), message);
        } catch (IOException | RuntimeException e) {
            return new LoadOutcome(
                    new TaskList(),
                    "Sorry, I couldn't load your saved tasks. Starting with an empty task list.");
        }
    }

    private void showStartupMessage(Ui targetUi) {
        if (!isStartupMessageShown && startupMessage != null) {
            targetUi.showStorageMessage(startupMessage);
        }
        isStartupMessageShown = true;
    }

    private void appendResponse(StringBuilder response, String message) {
        if (!response.isEmpty()) {
            response.append(System.lineSeparator());
        }
        response.append(message);
    }

    /** Holds tasks and any user-facing warning produced while loading them. */
    private record LoadOutcome(TaskList tasks, String message) {
    }
}
